[tool.poetry]
name = "flsk"
version = "0.1.0"
description = "Python flask"
authors = ["imausera"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
