version: "3.3"
services:
  flsk:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: care_modle:latest
    container_name: care_modle
    restart: always
    environment:
      FLASK_CONFIG: "development"
    ports:
      - "31004:8000"
    volumes:
      - ./log:/app/python/log
